In [1]:
import numpy as np

# Arrays

In [2]:
#vectors: 1D arrays
#matrices: 2D arrays

In [3]:
lst = [1,2,3]

In [4]:
lst

[1, 2, 3]

In [5]:
type(lst)

list

In [6]:
np.array(lst)

array([1, 2, 3])

In [7]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
type(mat)

list

In [9]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-In methods to create arrays

### arange

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,3)

array([0, 3, 6, 9])

# Zeros and Ones

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linspace

In [16]:
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
np.linspace(0,9,100)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

# Eye

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random

#### rand

In [19]:
np.random.rand(5)

array([0.50416868, 0.76993061, 0.24740155, 0.20482392, 0.90549815])

In [20]:
np.random.rand(5,4)

array([[0.13192593, 0.66291907, 0.15749834, 0.72259334],
       [0.39318352, 0.18880072, 0.19724594, 0.39432039],
       [0.49626387, 0.02264312, 0.12912484, 0.1792233 ],
       [0.16315989, 0.69685327, 0.11230004, 0.93225948],
       [0.57415043, 0.95278968, 0.43802533, 0.44557762]])

#### randn

In [21]:
np.random.randn(5,5)

array([[-0.04255335,  0.68965797, -0.92953169, -1.54818861, -1.08971639],
       [ 0.04200914, -0.02000018,  0.02259588,  0.86445119, -0.23357194],
       [-0.51770687, -1.97536486, -1.20148468,  0.95049655, -0.22051387],
       [-1.31175009,  0.3139736 ,  2.51809763,  0.5986902 ,  2.21993787],
       [ 0.05982217,  1.27676372,  1.68425122, -1.58078529,  0.56043795]])

#### randint

In [22]:
np.random.randint(1,100)

24

In [23]:
np.random.randint(1,105650, 20)

array([ 6964, 32736, 62129, 64201, 89911, 40827, 95605, 89588, 39896,
        5531, 56828, 20645,  6923, 39522, 56416, 91266, 12515, 87261,
       73395, 67349])

#### seed

In [31]:
np.random.seed(50)  #random_state

In [36]:
np.random.randint(1,10000)

8263

In [39]:
np.random.rand(3)

array([0.76053669, 0.31000935, 0.3465412 ])

# Attributes and Methods

In [44]:
ar = np.arange(30)

In [45]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
ranar = np.random.randint(0,50,20)

In [47]:
ranar

array([ 2, 12, 32,  3,  2, 10, 48, 46,  0, 29, 29, 30,  0, 11, 30, 26,  7,
       28, 24, 27])

# Reshape

In [58]:
ar1 = ar.reshape(2,15)

In [59]:
ar1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [49]:
ar.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [50]:
ar.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### max, min, argmax, argmin

In [51]:
ranar

array([ 2, 12, 32,  3,  2, 10, 48, 46,  0, 29, 29, 30,  0, 11, 30, 26,  7,
       28, 24, 27])

In [52]:
ranar.max()

48

In [53]:
ranar.argmax()

6

In [55]:
ranar.min()

0

In [56]:
ranar.argmin()

8

#### Shape

In [61]:
ar.shape

(30,)

### Reshape

In [63]:
ar.reshape(15,2).shape

(15, 2)

In [64]:
ar.dtype

dtype('int32')

In [65]:
ar3 = np.array([1.2,5.6,3.0,11.9])

In [66]:
ar3.dtype

dtype('float64')