In [4]:
import numpy as np #alias

In [8]:
ar = np.arange(0,11,2)
ar

array([ 0,  2,  4,  6,  8, 10])

# Bracket Index and Selection

In [9]:
ar[5]

10

In [11]:
ar[1:]

array([ 2,  4,  6,  8, 10])

In [13]:
ar[:3]

array([0, 2, 4])

In [14]:
ar[1:3]

array([2, 4])

# Broadcasting

In [15]:
ar

array([ 0,  2,  4,  6,  8, 10])

In [16]:
ar[0:3] = 23
ar

array([23, 23, 23,  6,  8, 10])

In [22]:
ar = np.arange(0,11,2)
ar

array([ 0,  2,  4,  6,  8, 10])

## Slicing

In [23]:
ar1 = ar[1:3]

In [24]:
ar1

array([2, 4])

In [25]:
ar

array([ 0,  2,  4,  6,  8, 10])

In [26]:
ar_copy = ar.copy()

In [27]:
ar_copy

array([ 0,  2,  4,  6,  8, 10])

In [28]:
ar_copy[:] = 99

In [29]:
ar_copy

array([99, 99, 99, 99, 99, 99])

In [30]:
ar

array([ 0,  2,  4,  6,  8, 10])

# Indexing(Matrices)

In [32]:
ar_mat = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [33]:
ar_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar_mat[1]

array([4, 5, 6])

In [35]:
ar_mat[1][2]

6

In [36]:
ar_mat[2][1]

8

In [37]:
ar_mat[2,1]

8

In [40]:
ar_mat[:2,1:]

array([[2, 3],
       [5, 6]])

In [41]:
ar_mat[1:,:2]

array([[4, 5],
       [7, 8]])

## Conditional Selection

In [42]:
ar

array([ 0,  2,  4,  6,  8, 10])

In [44]:
ar_bool = ar > 5

In [45]:
ar_bool

array([False, False, False,  True,  True,  True])

In [47]:
ar[ar_bool == False]

array([0, 2, 4])

In [48]:
ar[ar_bool]

array([ 6,  8, 10])

In [49]:
ar[ar>2]

array([ 4,  6,  8, 10])

In [50]:
ar[ar<8]

array([0, 2, 4, 6])

In [53]:
ar[(ar>2) & (ar < 8)]

array([4, 6])

In [55]:
ar[(ar<2) | (ar>8)]

array([ 0, 10])

In [54]:
x = 6
ar[ar>x]

array([ 8, 10])